* Cloning
When cloning, be sure to initiate the submodule, lua-table-persistance
#+BEGIN_SRC 
git submodule update --init --recursive
#+END_SRC
Run this inside the cloned repository.
* Quick set up

Drop this folder in your mpv scripts folder, (~/.config/mpv/scripts) on linux, and then watch shows.
A file will be created in that directory, LAST_WATCHED_MPV
This file will contain a simple list of shows, and what episode of them you last watched. 

* How it works
Upon opening a file, a .LAST_WATCHED_MPV is checked for in that directory, if one doesn't exist, it will be made.
The episode is then stripped of some special characters, and anything in brackets, or parens, and then has it's numbers parsed out from the rest of it.
These then form the episode name, and episode number, and are written to the text file, plus put into a map of episodes, plus how far into them you are.
In total, the text file will contain for each series, 
 - Most recently opened episode
 - How far into that episode you were
 - Percentage into that episode you got
 - Map of episodes opened, and percentage gotten into each one.
   
Series must be consistently named.


* Warnings
This will overrite any other file called LAST_WATCHED_MPV in the directory of the media. 

LAST_WATCHED_MPV is read via dofile, so a could carefully crafted filename on a media file could carry a bad payload, and inject whatever script it wants into mpv.
This should be pretty obvious though, as it would be in the filename, so should only be an issue if random people can submit random files to your mpv...

If the media file is only open for a second or two, the text file might not be updated.

File is .LAST_WATCHED_MPV, so it'll be hidden.

* Note
--script=~/.config/mpv/scripts/last_watched/last_watched.lua
Points to it directly, but will probably miss the persistence script it depends on.




